// CSV dışa aktarma — tüm sayfaların 'CSV indir' düğmeleri buraya bağlanır.
function exportForecastCSV(){csvDownload('PharmaInsight_Forecast.csv',['Temsilci','Hedef','Mevcut Satış','Mevcut Realizasyon','Forecast','Tahmini Realizasyon','Günlük Gerekli','Kalan Gün'],repForecastRows().map(x=>[x.name,x.target,x.sales,x.real,x.fc.forecast,x.fc.projectedReal,x.fc.requiredDaily,x.fc.remaining]))}

function csvDownload(name,headers,rows){const clean=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[headers,...rows].map(r=>r.map(clean).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function exportRepCSV(){csvDownload('PharmaInsight_Temsilci_360.csv',['Temsilci','Pozisyon','Hedef','Satış','Realizasyon','Plan Uyum','Kaveraj','Frekans','Seleksiyon','Sipariş','Eczane','Yanlış Brick','Risk'],allRepMetrics().map(x=>[x.name,x.row.positionCode,x.target,x.sales,x.real,x.plan,x.coverage,x.freq,x.sel.length,x.orders.length,x.pharmacies,x.wrong,x.risk]))}
function exportBrickCSV(){csvDownload('PharmaInsight_Brick_360.csv',['Brick','Temsilci','İl','Hedef','Satış','Açık','Realizasyon','Seçki','Havuz','Ziyaret','Plan Uyum','Sipariş','Adet'],allBrickMetrics().map(x=>[x.name,x.owner,province(x.name),x.target,x.sales,x.gap,x.real,x.sel.length,x.pool.length,x.visits,x.plan,x.orders.length,x.qty]))}
function exportProductCSV(){csvDownload('PharmaInsight_Urun_Performans.csv',['Ürün','Hedef','Satış','Açık','Realizasyon'],productMetrics().map(x=>[x.product,x.target,x.sales,x.gap,x.real]))}
function exportPlanCSV(){csvDownload('PharmaInsight_Plan_Frekans.csv',['Temsilci','Ziyaret','Planlı','Plan Uyum','Seleksiyon','Kaveraj','Frekans Uyumlu','Hedefli','Frekans'],allRepMetrics().map(x=>[x.name,x.visits.length,x.visits.filter(v=>v.planned).length,x.plan,x.sel.length,x.coverage,x.compliant,x.withTarget,x.freq]))}
function exportDecisionCSV(){csvDownload('PharmaInsight_Aksiyon_Merkezi.csv',['Tip','Konu','Sorumlu','Neden','Finansal Etki','Durum','Son Tarih','Hedef','Gerçekleşen','Aksiyon','Not'],decisionRows().map(x=>[x.type,x.subject,x._rec.owner,x.reason,x.impact,x._rec.status,x._rec.due,x._rec.targetValue,x._rec.actualValue,x._rec.customAction,x._rec.note]))}
function exportCustomerCSV(){const rows=customerRows();csvDownload('PharmaInsight_Musteri_360.csv',['Müşteri','Branş','Kurum','Brick','Temsilci'],rows.map(x=>[x.customer,x.specialty,x.institution,x.brick,x.rep]))}
function exportQualityCSV(){const q=qualityData();csvDownload('PharmaInsight_Veri_Kalitesi.csv',['Kontrol','Sayı/Değer','Durum'],[['Real organizasyon',q.realRegions.join(', '),'Temel'],['Kümüle organizasyon',q.kumRegions.join(', '),q.mismatchK?'Uyumsuz':'Uyumlu'],['YTD organizasyon',q.ytdRegions.join(', '),q.mismatchY?'Uyumsuz':'Uyumlu'],['Yanlış brick',q.wrong,q.wrong?'Kontrol':'Temiz'],['Eski temsilci kaydı',q.oldRep,q.oldRep?'Kontrol':'Temiz'],['Mükerrer seçki',q.duplicate,q.duplicate?'Kontrol':'Temiz'],['Havuzda bulunmayan',q.missingPool,q.missingPool?'Kontrol':'Temiz']])}
function exportGrowCSV(){const s=growSessions(),criteria=growAllCriteria();const headers=['Durum','Temsilci','Başlangıç','Takip','Dönem','IMS Dönemi','Genel Puan','Puanlanan Kriter',...criteria.map(c=>c.id.toUpperCase()+' - '+c.section),'Yönetici Yorumu','G','R','O','W'];const rows=s.map(x=>[x.status,x.rep,x.startDate,x.endDate,x.period,x.imsPeriod,x.avg,x.count,...criteria.map(c=>x.scores?.[c.id]||''),x.managerComment,x.goal,x.reality,x.options,x.way]);csvDownload('PharmaInsight_GROW_Gelismis.csv',headers,rows)}
function exportSingleRep(rn){const x=allRepMetrics().find(r=>r.rn===rn);if(!x)return;csvDownload(`Temsilci_${x.name}.csv`,['Metrik','Değer'],[['Hedef',x.target],['Satış',x.sales],['Realizasyon',x.real],['Plan uyum',x.plan],['Kaveraj',x.coverage],['Frekans',x.freq],['Seleksiyon',x.sel.length],['Sipariş',x.orders.length],['Risk',x.risk]])}
function exportSingleBrick(name){const x=allBrickMetrics().find(b=>norm(b.name)===norm(name));if(!x)return;csvDownload(`Brick_${x.name}.csv`,['Metrik','Değer'],[['Temsilci',x.owner],['Hedef',x.target],['Satış',x.sales],['Açık',x.gap],['Realizasyon',x.real],['Seçki',x.sel.length],['Havuz',x.pool.length],['Ziyaret',x.visits],['Sipariş',x.orders.length]])}
