// Dönem/IMS sınırları, run-rate forecast ve senaryo simülasyonu hesaplamaları.
function periodRowsFor(key){return DATA.realPeriods?.[key]?.rows||[]}
function compactPeriod(key){const p=DATA.realPeriods?.[key];if(!p)return null;const rows=p.rows||[],regions=[...new Set(rows.map(r=>r.region).filter(Boolean))],region=regions.find(x=>norm(x).includes('CENGIZ'))||regions[0]||'',mine=rows.filter(r=>r.region===region),bm=mine.find(r=>r.level==='BM'),reps=mine.filter(r=>r.level==='TTT');let target=realTotal(bm,'HEDEF')||reps.reduce((a,r)=>a+realTotal(r,'HEDEF'),0),sales=realTotal(bm,'SATIS')||reps.reduce((a,r)=>a+realTotal(r,'SATIS'),0);return {key,label:imsPeriodLabel(key),target,sales,real:target?100*sales/target:0,gap:Math.max(0,target-sales),rows:mine.length,file:p.fileName||'',sheet:p.sheet||key}}
function sortedIMSPeriods(){const rank=x=>/^\d{2}\|\d{2}$/.test(x)?Number(x.replace('|','')):x==='Q1'?2604:x==='Q2'?2605:x==='Q3'?2606:x==='Q4'?2607:x==='H1'?2608:x==='H2'?2609:9999;return Object.keys(DATA.realPeriods||{}).sort((a,b)=>rank(a)-rank(b))}
function fieldMonthMetric(m){const visits=(DATA.ziyaret||[]).filter(x=>String(x.date).startsWith(m)),orders=(DATA.siparis||[]).filter(x=>String(x.date).startsWith(m));return {month:m,visits:visits.length,planned:visits.filter(x=>x.planned).length,plan:visits.length?100*visits.filter(x=>x.planned).length/visits.length:0,customers:new Set(visits.map(x=>norm(x.customer))).size,orders:orders.length,qty:orders.reduce((a,x)=>a+n(x.qty),0),pharmacies:new Set(orders.map(x=>norm(x.pharmacy))).size}}
function periodBounds(k){const d=new Date(DATA.generatedAt||Date.now());let start,end;if(/^\d{2}\|\d{2}$/.test(k)){const [yy,mm]=k.split('|').map(Number);start=new Date(2000+yy,mm-1,1);end=new Date(2000+yy,mm,0)}else if(/^Q[1-4]$/.test(k)){const q=Number(k[1]),m=(q-1)*3;start=new Date(d.getFullYear(),m,1);end=new Date(d.getFullYear(),m+3,0)}else if(k==='H1'){start=new Date(d.getFullYear(),0,1);end=new Date(d.getFullYear(),6,0)}else if(k==='H2'){start=new Date(d.getFullYear(),6,1);end=new Date(d.getFullYear(),12,0)}else{return null}const asof=new Date(Math.min(Math.max(d.getTime(),start.getTime()),end.getTime()));const total=Math.floor((end-start)/86400000)+1,elapsed=Math.floor((asof-start)/86400000)+1,remaining=Math.max(0,total-elapsed);return {start,end,total,elapsed,remaining,asof}}
function forecastMetric(target,sales,key=STATE.imsPeriod){const b=periodBounds(key);if(!b||!target||!sales)return {available:false,target,sales,forecast:sales,projectedReal:target?100*sales/target:0,requiredDaily:0,currentDaily:0,remaining:b?.remaining||0};const currentDaily=sales/Math.max(1,b.elapsed),forecast=currentDaily*b.total,requiredDaily=Math.max(0,target-sales)/Math.max(1,b.remaining);return {available:true,target,sales,forecast,projectedReal:100*forecast/target,requiredDaily,currentDaily,remaining:b.remaining,elapsed:b.elapsed,total:b.total}}
function repForecastRows(){return allRepMetrics().filter(x=>x.rn!=='BOS POZISYON').map(x=>({...x,fc:forecastMetric(x.target,x.sales)})).sort((a,b)=>b.gap-a.gap)}
function scenarioResult(){const r=regionMetric(),f=forecastMetric(r.h,r.s),s=STATE.scenario||{plan:0,freq:0,orders:0};const uplift=(n(s.plan)*.0008+n(s.freq)*.001+n(s.orders)*.0006),base=f.available?f.forecast:r.s,scenario=base*(1+uplift);return {base,scenario,real:r.h?100*scenario/r.h:0,uplift:uplift*100}}
function scenarioField(k,v){STATE.scenario[k]=n(v);const s=scenarioResult();document.getElementById('sc-'+k+'-v').textContent='%'+v;document.getElementById('scenarioSales').textContent=fmtTL(s.scenario);document.getElementById('scenarioReal').textContent=fmtPct(s.real);document.getElementById('scenarioUplift').textContent='Baz tahmine göre +%'+s.uplift.toFixed(1)}
function trendSvg(){const list=sortedIMSPeriods().filter(k=>/^\d{2}\|\d{2}$/.test(k)).map(compactPeriod).filter(Boolean);if(!list.length)return '<div class="empty">Aylık IMS dönemi bulunamadı</div>';const W=760,H=250,pad=42,max=Math.max(...list.flatMap(x=>[x.target,x.sales]),1),xs=i=>pad+i*(W-pad*2)/Math.max(1,list.length-1),ys=v=>H-pad-v/max*(H-pad*2);const target=list.map((x,i)=>`${xs(i)},${ys(x.target)}`).join(' '),sales=list.map((x,i)=>`${xs(i)},${ys(x.sales)}`).join(' ');return `<svg class="trend-svg" viewBox="0 0 ${W} ${H}"><line class="trend-axis" x1="${pad}" y1="${H-pad}" x2="${W-pad}" y2="${H-pad}"></line><polyline class="trend-target" points="${target}"></polyline><polyline class="trend-sales" points="${sales}"></polyline>${list.map((x,i)=>`<circle class="trend-point" cx="${xs(i)}" cy="${ys(x.sales)}" r="5"></circle><text class="trend-label" x="${xs(i)}" y="${H-16}" text-anchor="middle">${esc(x.label.replace(' 2026',''))}</text><text class="trend-value" x="${xs(i)}" y="${Math.max(12,ys(x.sales)-10)}" text-anchor="middle">${fmtPct(x.real)}</text>`).join('')}</svg><div class="map-legend"><span class="map-dot" style="background:#1769ff"></span>Satış <span style="border-top:2px dashed #9aa8ba;width:13px"></span>Hedef</div>`}
