// Uygulama iskeleti: navigasyon, sayfa yönlendirme, genel modal/arama ve açılış bootstrap'ı.
// Sayfa render fonksiyonlarının kendisi src/pages/*.js içindedir; burada yalnızca
// hangi sayfanın ne zaman çizileceğini yöneten 'kabuk' mantığı bulunur.
function renderNav(){let section='';document.getElementById('nav').innerHTML=navItems.map(it=>{const [id,label,ic,sec]=it;let h='';if(sec&&sec!==section){section=sec;h=`<div class="nav-section">${sec}</div>`}return h+`<button class="nav-btn ${STATE.page===id?'active':''}" onclick="go('${id}')">${icon(ic)}<span>${label}</span>${id==='quality'&&qualityData().critical?`<span class="nav-badge">${qualityData().critical}</span>`:''}</button>`}).join('')}
function renderPeriod(){const el=document.getElementById('periodSelect');if(!el)return;const opts=[...IDX.months].reverse().map(m=>`<option value="${m}" ${STATE.period===m?'selected':''}>${monthLabel(m)}</option>`).join('')+`<option value="all" ${STATE.period==='all'?'selected':''}>Tüm saha dönemi</option>`;el.innerHTML=opts}
function renderIMSPeriod(){const el=document.getElementById('imsPeriodSelect');if(!el)return;const periods=DATA.realPeriods||{};const order=Object.keys(periods).sort((a,b)=>{const rank=x=>/^\d{2}\|\d{2}$/.test(x)?Number(x.replace('|','')):x==='Q3'?30000:x==='H2'?40000:50000;return rank(a)-rank(b)});el.innerHTML=order.map(k=>{const p=periods[k],mode=n(p.salesTotal)>0?'':' · hedef';return `<option value="${esc(k)}" ${STATE.imsPeriod===k?'selected':''}>${esc(imsPeriodLabel(k)+mode)}</option>`}).join('')||`<option>${esc(DATA.real?.sheet||'IMS')}</option>`}
function renderSideStatus(){const q=qualityData(),r=regionMetric();document.getElementById('sideStatus').innerHTML=`<div style="display:flex;justify-content:space-between"><b>Veri Durumu</b><span class="${q.critical?'amber':'ok'}">${q.critical?'Kontrol Gerekli':'Aktif'}</span></div><div style="margin-top:8px">IMS dönemi: <b>${esc(imsPeriodLabel(IDX.realSource?.sheet||STATE.imsPeriod))}</b><br>Saha ayı: <b>${esc(monthLabel(STATE.period))}</b><br>Kaynaklar: IMS · Seleksiyon · Ziyaret · Havuz · Sipariş</div><div style="margin-top:8px">${fmtN(r.bricks)} brick · ${fmtN(r.selection)} seçki</div>`}
function changePeriod(v){STATE.period=v;IDX.cache.clear();renderSideStatus();renderPage()}
function changeIMSPeriod(v){STATE.imsPeriod=v;reindex();renderPage()}
function go(page){STATE.page=page;STATE.rep=null;STATE.brick=null;STATE.customerPage=0;closeSidebar();renderNav();renderPage();window.scrollTo(0,0)}
function hero(title,sub,actions=''){return `<div class="hero"><div><h1>${title}</h1><p>${sub}</p></div><div class="hero-actions">${actions}</div></div>`}
function kpi(label,value,foot,color='blue',iconClass='icon-blue'){return `<div class="card kpi"><div class="kpi-top"><div class="kpi-icon ${iconClass}">•</div><div class="kpi-label">${label}</div></div><div class="kpi-value ${color}">${value}</div><div class="kpi-foot">${foot}</div></div>`}
function progress(v){const x=clamp(n(v),0,130);return `<div class="progress"><span style="width:${Math.min(x,100)}%;background:${pctColor(x)}"></span></div>`}

function changeMapLayer(v){STATE.mapLayer=v;renderPage()}
function filterRows(id,q){q=norm(q);document.querySelectorAll('#'+id+' tbody tr').forEach(r=>r.style.display=!q||r.dataset.search?.includes(q)?'':'none')}
function renderPage(){const root=document.getElementById('content');const renderers={main:renderDashboard,decisions:renderDecisions,forecast:renderForecast,reps:renderReps,bricks:renderBricks,customers:renderCustomers,products:renderProducts,plan:renderPlan,archive:renderArchive,quality:renderQuality,grow:renderGrow,reports:renderReports,upload:renderUpload};root.innerHTML=(renderers[STATE.page]||renderDashboard)();if(STATE.page==='customers')renderCustomerBody();renderNav()}
function showModal(html){document.getElementById('modal').innerHTML=html;document.getElementById('modalBg').classList.add('show')}
function closeModal(){document.getElementById('modalBg').classList.remove('show')}
function openLocalInsight(){const r=regionMetric(),reps=allRepMetrics().filter(x=>x.rn!=='BOS POZISYON').sort((a,b)=>b.risk-a.risk),bricks=allBrickMetrics().sort((a,b)=>b.gap-a.gap),q=qualityData();showModal(`<div class="detail-head"><div class="detail-avatar">AI</div><div><div class="detail-name">Yerel Yönetici Analizi</div><div class="detail-meta">IMS + seleksiyon + ziyaret + frekans + sipariş + veri kalitesi</div></div><button class="modal-close" onclick="closeModal()">×</button></div><div class="tab-content"><div class="insight-grid"><div class="insight" style="--accent:${pctColor(r.real)}"><div class="insight-k">Genel Durum</div><div class="insight-v">Bölge ${fmtTL(r.s)} satışla ${fmtPct(r.real)} realizasyonda. Hedef açığı ${fmtTL(r.gap)}.</div></div><div class="insight" style="--accent:#7447f5"><div class="insight-k">Saha Disiplini</div><div class="insight-v">Plan uyumu ${fmtPct(r.plan)}, frekans uyumu ${fmtPct(r.freq)}, seçili müşteri kaverajı ${fmtPct(r.coverage)}.</div></div><div class="insight" style="--accent:${q.critical?'#ef3f53':'#00a878'}"><div class="insight-k">Veri Güveni</div><div class="insight-v">${q.critical?`${q.critical} kritik veri kalite başlığı var. Kümüle/YTD organizasyon uyumunu kontrol et.`:'Kritik veri kalite sorunu görünmüyor.'}</div></div></div><div class="section-space"></div><div class="card"><div class="card-head"><div class="card-title">Öncelik Sıralaması</div></div><div style="padding:12px;font-size:10px;line-height:1.8"><b>1. Temsilci:</b> ${esc(reps[0]?.name||'—')} — risk ${Math.round(reps[0]?.risk||0)}, realizasyon ${fmtPct(reps[0]?.real)}, frekans ${fmtPct(reps[0]?.freq)}.<br><b>2. Brick:</b> ${esc(bricks[0]?.name||'—')} — ${fmtTL(bricks[0]?.gap||0)} açık, ${fmtPct(bricks[0]?.real)} realizasyon.<br><b>3. Saha aksiyonu:</b> Frekans altında kalan seçili müşterileri yüksek satış açığı olan bricklerle eşleştir ve haftalık rotaya al.<br><b>4. Veri aksiyonu:</b> Güncel G3 Akdeniz Kümüle ve YTD dosyaları yüklenene kadar pazar/rakip yorumunu Real IMS ile sınırlı tut.</div></div></div>`)}
function runGlobalSearch(){const q=norm(document.getElementById('globalSearch').value);if(!q)return;const rep=allRepMetrics().find(x=>norm(x.name).includes(q));if(rep)return openRep(rep.rn);const brick=allBrickMetrics().find(x=>norm(x.name).includes(q));if(brick)return openBrick(brick.name);const prod=productMetrics().find(x=>norm(x.product).includes(q));if(prod){STATE.page='products';renderPage();setTimeout(()=>openProduct(prod.product),0);return}STATE.query=document.getElementById('globalSearch').value;STATE.page='customers';renderPage()}
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
setTimeout(()=>{reindex();renderPage();document.getElementById('loading').style.display='none'},20);
