// Yönetici Özeti (main) sayfası.
function renderProvinceMap(prov){const by=new Map(prov.map(x=>[x.name,x])),layer=STATE.mapLayer||'real';const defs=[['Muğla','M18 132 L74 112 L108 132 L92 176 L42 184 L12 160 Z',55,150],['Denizli','M76 78 L131 65 L154 104 L108 132 L74 112 Z',111,96],['Burdur','M139 108 L188 96 L208 132 L178 165 L113 151 L108 132 Z',160,130],['Isparta','M180 65 L231 53 L252 94 L208 132 L188 96 Z',216,84],['Antalya','M94 176 L113 151 L178 165 L220 148 L257 177 L231 218 L145 226 L82 209 Z',170,190],['Afyon','M154 30 L227 18 L267 49 L231 53 L180 65 L139 58 Z',202,43],['Konya','M252 54 L350 38 L421 76 L400 151 L329 177 L257 177 L220 148 L208 132 L252 94 Z',329,104],['Karaman','M270 179 L329 177 L383 160 L401 205 L344 231 L287 219 Z',339,202]];const vals=prov.map(x=>n(x[layer])),max=Math.max(...vals,1);const color=m=>{const v=n(m[layer]);if(layer==='real'||layer==='plan'||layer==='freq')return v>=100?'#a9e7d3':v>=85?'#ffe0a0':v>0?'#ffbec6':'#e8edf4';const ratio=v/max;return ratio>.75?'#ef6b78':ratio>.45?'#f5a564':ratio>.2?'#ffd79b':'#dbeafe'};const val=m=>layer==='sales'||layer==='gap'?fmtTL(m[layer]):layer==='orders'?fmtN(m.orders):fmtPct(m[layer]);const labels={real:'Realizasyon',gap:'Satış Açığı',sales:'Satış',plan:'Plan Uyumu',freq:'Frekans',orders:'Sipariş Adedi'};const svg=defs.map(([name,path,x,y])=>{const m=by.get(name)||{real:0,sales:0,gap:0,plan:0,freq:0,orders:0,bricks:0};return `<g onclick="filterProvince('${name}')"><path class="province-shape" d="${path}" fill="${color(m)}"><title>${name}: ${labels[layer]} ${val(m)} · ${m.bricks} brick</title></path><text class="province-label" x="${x}" y="${y}">${name}</text><text class="province-value" x="${x}" y="${y+13}">${val(m)}</text></g>`}).join('');const total=prov.reduce((a,x)=>a+n(x[layer]),0),worst=[...prov].sort((a,b)=>layer==='real'||layer==='plan'||layer==='freq'?n(a[layer])-n(b[layer]):n(b[layer])-n(a[layer]))[0];return `<div class="map-layer-bar">${[['real','Realizasyon'],['gap','Açık'],['sales','Satış'],['plan','Plan'],['freq','Frekans'],['orders','Sipariş']].map(x=>`<button class="map-layer-btn ${layer===x[0]?'active':''}" onclick="changeMapLayer('${x[0]}')">${x[1]}</button>`).join('')}</div><div class="province-map-wrap"><svg class="province-map" viewBox="0 0 440 245" role="img" aria-label="G3 Akdeniz performans haritası">${svg}</svg></div><div class="map-summary"><div><span>Katman</span><b>${labels[layer]}</b></div><div><span>En kritik il</span><b>${esc(worst?.name||'—')}</b></div><div><span>Değer</span><b>${worst?val(worst):'—'}</b></div><div><span>İl sayısı</span><b>${prov.length}</b></div></div>`}
function renderDashboard(){
 const r=regionMetric(),dec=decisionData().slice(0,5),reps=r.reps,products=productMetrics().slice(0,5),prov=provinceMetrics();const worst=reps.filter(x=>x.rn!=='BOS POZISYON').sort((a,b)=>b.risk-a.risk)[0];
 const actions=`<button class="ghost-btn" onclick="exportRepCSV()">Excel/CSV</button><button class="ghost-btn" onclick="copyWhatsApp()">WhatsApp Özeti</button><button class="ghost-btn" onclick="go('forecast')">Trend & Forecast</button><button class="primary-btn" onclick="go('decisions')">Aksiyonları Aç</button>`;
 const decisionCards=dec.map((d,i)=>`<div class="decision" onclick="openDecision(${i})"><div class="decision-top"><span class="rank" style="background:${d.color}">${i+1}</span><div class="decision-name">${esc(d.type)}</div></div><dl><dt>Konu</dt><dd>${esc(d.subject)}</dd><dt>Etki</dt><dd>${d.impact?fmtTL(d.impact):'Veri yapısı'}</dd><dt>Neden</dt><dd title="${esc(d.reason)}">${esc(d.reason)}</dd></dl><div class="decision-action">Sonraki aksiyon: ${esc(d.action)}</div></div>`).join('');
 const repBars=reps.filter(x=>x.rn!=='BOS POZISYON').sort((a,b)=>b.sales-a.sales).slice(0,7).map(x=>`<div class="bar-row"><div class="bar-label">${esc(x.name)}</div><div class="bar-track"><div class="bar-fill" style="width:${clamp(x.real,0,100)}%;background:${pctColor(x.real)}"></div></div><div class="bar-val">${fmtPct(x.real)}</div></div>`).join('');
 const productBars=products.map((x,i)=>`<div class="bar-row"><div class="bar-label">${esc(x.product)}</div><div class="bar-track"><div class="bar-fill" style="width:${clamp(x.sales/(products[0]?.sales||1)*100,2,100)}%;background:${['#1769ff','#00a878','#7447f5','#f59e0b','#00a9c7'][i]}"></div></div><div class="bar-val">${fmtTL(x.sales)}</div></div>`).join('');
 const territoryMap=renderProvinceMap(prov);const po=periodOrders(DATA.siparis||[]),orderQty=po.reduce((a,x)=>a+n(x.qty),0),activePharmacies=new Set(po.map(x=>norm(x.pharmacy))).size;
 const alerts=decisionData().slice(0,3).map((d,i)=>`<div class="alert-item"><div class="alert-dot" style="background:${d.color}18;color:${d.color}">!</div><div><div class="alert-name">${esc(d.subject)}</div><div class="alert-sub">${esc(d.reason)}</div></div><div class="alert-time">${i+1}. öncelik</div></div>`).join('');
 const aiText=worst?`${worst.name}, ${fmtPct(worst.real)} realizasyon ve ${fmtPct(worst.freq)} frekans uyumuyla en yüksek birleşik risk skoruna sahip. ${worst.riskBricks} brick %70'in altında. Öncelik: ${fmtTL(worst.gap)} satış açığını, frekans altında kalan seçili müşteriler üzerinden yönetmek.`:'Risk analizi için yeterli veri bulunamadı.';
 return `<div class="with-rail"><div class="page-main">${hero('G3 Akdeniz Bölge Komuta Merkezi',`IMS ${esc(imsPeriodLabel(IDX.realSource?.sheet||STATE.imsPeriod))} · Saha ${monthLabel(STATE.period)} · Son veri: ${new Date(DATA.generatedAt||Date.now()).toLocaleString('tr-TR')}`,actions)}
 <div class="scope-note"><span>ℹ</span><div><b>İki dönem ayrı çalışır:</b> IMS Dönemi satış, hedef, realizasyon, ürün, temsilci, brick ve il haritasını; Saha Ayı ziyaret, plan uyumu, frekans, kaveraj ve sipariş metriklerini değiştirir.</div></div>
 <div class="kpi-grid">${kpi('Bölge Satış',fmtTL(r.s),`Hedef ${fmtTL(r.h)}`,'blue','icon-blue')}${kpi('Realizasyon',fmtPct(r.real),`Açık ${fmtTL(r.gap)}`,r.real>=85?'green':'red',r.real>=85?'icon-green':'icon-red')}${kpi('Plan Uyumu',fmtPct(r.plan),`${fmtN(r.visits.length)} ziyaret`,'amber','icon-amber')}${kpi('Frekans Uyumu',fmtPct(r.freq),`Kaveraj ${fmtPct(r.coverage)}`,'purple','icon-purple')}${kpi('Sipariş Adedi',fmtN(orderQty),`${fmtN(activePharmacies)} aktif eczane`,'green','icon-green')}${kpi('Riskli Brick',fmtN(r.riskBricks),`${r.bricks} brick içinde`,'red','icon-red')}</div>
 <div class="card" style="margin-bottom:12px"><div class="card-head"><div><div class="card-title">Karar Merkezi</div><div class="card-sub">En kritik fırsat ve riskler; finansal etki ve saha nedenleriyle sıralanır</div></div><button class="link-btn" onclick="go('decisions')">Tümünü gör →</button></div><div class="decision-row">${decisionCards}</div></div>
 <div class="dash-row"><div class="card"><div class="card-head"><div><div class="card-title">Temsilci Performansı</div><div class="card-sub">Real IMS hedef/satış realizasyonu</div></div><button class="link-btn" onclick="go('reps')">Detay →</button></div><div class="bar-list">${repBars}</div></div><div class="card"><div class="card-head"><div><div class="card-title">Ürün Performansı</div><div class="card-sub">Bölge satışına göre ilk 5 ürün</div></div><button class="link-btn" onclick="go('products')">Tümü →</button></div><div class="bar-list">${productBars}</div></div><div class="card"><div class="card-head"><div><div class="card-title">Bölge Isı Haritası</div><div class="card-sub">İl bazında realizasyon ve satış</div></div></div>${territoryMap}</div></div>
 <div class="card table-card"><div class="card-head"><div><div class="card-title">Temsilci 360° Özet</div><div class="card-sub">IMS + seleksiyon + plan + frekans + sipariş + risk</div></div><button class="link-btn" onclick="go('reps')">Tümünü gör →</button></div>${repTable(reps)}</div>
 </div><aside class="right-rail"><div class="card ai-card"><div class="ai-title">Yönetici İçgörüsü <span class="ai-pill">YEREL</span></div><div class="ai-text">${esc(aiText)}</div><button class="ai-btn" onclick="openLocalInsight()">Detaylı analizi aç →</button><div class="ai-orb"></div></div><div class="card rail-card"><div class="card-head"><div class="card-title">Uyarılar</div><button class="link-btn" onclick="go('decisions')">Tümü</button></div><div class="alert-list">${alerts}</div></div><div class="card rail-card"><div class="card-head"><div class="card-title">Hızlı Aksiyonlar</div></div><div class="quick-grid"><button class="quick q-blue" onclick="go('decisions')">Aksiyon Planı</button><button class="quick q-green" onclick="go('forecast')">Forecast</button><button class="quick q-green" onclick="go('reports')">Rapor Oluştur</button><button class="quick q-amber" onclick="go('plan')">Ziyaret Planı</button><button class="quick q-purple" onclick="go('grow')">Koçluk Ataması</button></div></div><div class="card rail-card"><div class="card-head"><div class="card-title">Rapor Çıktıları</div><button class="link-btn" onclick="go('reports')">Tümü</button></div><div class="report-list"><div class="report-item" onclick="printPage()"><span class="report-ico">P</span>Bölge Performans Raporu<span class="report-type">PDF</span></div><div class="report-item" onclick="exportRepCSV()"><span class="report-ico">X</span>Temsilci Performans Raporu<span class="report-type">CSV</span></div><div class="report-item" onclick="exportBrickCSV()"><span class="report-ico">B</span>Brick 360° Raporu<span class="report-type">CSV</span></div></div></div></aside></div>`
}
function repTable(reps){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Temsilci</th><th>Brick</th><th class="num">Satış</th><th>Realizasyon</th><th>Plan</th><th>Frekans</th><th>Seleksiyon</th><th>Risk</th></tr></thead><tbody>${reps.map(x=>`<tr class="click" onclick="openRep('${esc(x.rn)}')"><td><b>${esc(x.name)}</b></td><td>${x.bricks.length}</td><td class="num mono">${fmtTL(x.sales)}</td><td>${progress(x.real)}<div style="margin-top:4px">${fmtPct(x.real)}</div></td><td><span class="badge ${perfClass(x.plan||0)}">${fmtPct(x.plan)}</span></td><td><span class="badge ${perfClass(x.freq||0)}">${fmtPct(x.freq)}</span></td><td>${fmtN(x.sel.length)} <span style="color:var(--muted2)">/220</span></td><td><span class="badge ${riskClass(x.risk)}"><span class="dot" style="background:${x.risk>=65?'#ef3f53':x.risk>=35?'#f59e0b':'#00a878'}"></span>${Math.round(x.risk)}</span></td></tr>`).join('')}</tbody></table></div>`}
