// Ürün & Rakip (products) sayfası.
function productMetrics(){if(!IDX.bm)return[];return Object.keys(IDX.bm.values?.HEDEF||{}).filter(p=>p!=='TOPLAM').map(p=>{const h=realTotal(IDX.bm,'HEDEF',p),s=realTotal(IDX.bm,'SATIS',p);return {product:p,target:h,sales:s,gap:Math.max(0,h-s),real:h?100*s/h:rowPerf(IDX.bm,p)}}).filter(x=>x.target||x.sales).sort((a,b)=>b.sales-a.sales)}
function renderProducts(){
  const list=productMetrics();const q=qualityData();
  const listHtml=`${q.mismatchK||q.mismatchY?`<div class="card card-pad" style="border-left:4px solid var(--amber);margin-bottom:12px"><b style="font-size:10px">Rakip/pazar verisi güvenlik kilidi</b><div style="font-size:9px;color:var(--muted);margin-top:5px">Kümüle ve/veya YTD dosyası güncel G3 Akdeniz organizasyonuyla eşleşmiyor. Yanlış pazar kıyası üretmemek için bu ekran Real IMS hedef/satış verisini kullanıyor. Veri Kalitesi sayfasında ayrıntıyı görebilirsin.</div></div>`:''}<div class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Ürün</th><th class="num">Hedef</th><th class="num">Satış</th><th class="num">Açık</th><th>Realizasyon</th><th>En Güçlü Temsilci</th><th>En Riskli Brick</th></tr></thead><tbody>${list.map(p=>{const rep=allRepMetrics().map(r=>({name:r.name,real:rowPerf(r.row,p.product),sales:realTotal(r.row,'SATIS',p.product)})).sort((a,b)=>b.sales-a.sales)[0];const brick=IDX.bricks.map(b=>({name:b.brick,real:rowPerf(b,p.product),gap:Math.max(0,realTotal(b,'HEDEF',p.product)-realTotal(b,'SATIS',p.product))})).sort((a,b)=>b.gap-a.gap)[0];return `<tr class="click ${STATE.product===p.product?'sel':''}" onclick="openProduct('${escAttr(p.product)}')"><td><b>${esc(p.product)}</b></td><td class="num">${fmtTL(p.target)}</td><td class="num">${fmtTL(p.sales)}</td><td class="num red">${fmtTL(p.gap)}</td><td>${badge(p.real)}</td><td>${esc(rep?.name||'—')} · ${fmtPct(rep?.real)}</td><td>${esc(brick?.name||'—')} · ${fmtPct(brick?.real)}</td></tr>`}).join('')}</tbody></table></div></div>`;
  const detail=STATE.product?`<button class="ghost-btn md-detail-back" onclick="STATE.product=null;renderPage()">← Liste</button>${renderProductDetail(STATE.product)}`:`<div class="md-empty"><div class="md-empty-ic">📦</div><div>Detayları görmek için soldan bir <b>ürün seç</b></div></div>`;
  return `${hero('Ürün & Rakip','Ürün bazında bölge, temsilci ve brick performansını analiz eder',`<button class="ghost-btn" onclick="exportProductCSV()">CSV indir</button>`)}<div class="md-shell ${STATE.product?'has-detail':''}"><div class="md-list">${listHtml}</div><div class="md-detail">${detail}</div></div>`;
}
function renderProductDetail(product){
  const reps=allRepMetrics().map(r=>({name:r.name,target:realTotal(r.row,'HEDEF',product),sales:realTotal(r.row,'SATIS',product),real:rowPerf(r.row,product)})).filter(x=>x.target||x.sales).sort((a,b)=>b.sales-a.sales),bricks=IDX.bricks.map(b=>({name:b.brick,owner:displayRep(b.repName),target:realTotal(b,'HEDEF',product),sales:realTotal(b,'SATIS',product),real:rowPerf(b,product)})).filter(x=>x.target||x.sales).sort((a,b)=>(b.target-b.sales)-(a.target-a.sales));
  return `<div class="pi-ws-card"><div class="detail-head"><div class="detail-avatar">Ü</div><div><div class="detail-name">${esc(product)}</div><div class="detail-meta">Temsilci ve brick katkı analizi</div></div></div><div class="pi-panorama"><div class="pi-panorama-col">${piPanel('Temsilci Dağılımı',productDetailTable(reps.map(x=>({p:x.name,h:x.target,s:x.sales,r:x.real}))),'','tall')}</div><div class="pi-panorama-col">${piPanel('Brick Açıkları',productDetailTable(bricks.slice(0,30).map(x=>({p:x.name,h:x.target,s:x.sales,r:x.real}))),'','tall')}</div></div></div>`;
}
function openProduct(product){STATE.page='products';STATE.product=product;renderNav();renderPage()}
